# Generated by Django 4.1.5 on 2023-03-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_post_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
