# Generated by Django 4.1.5 on 2023-04-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='poll',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
    ]
