# Generated by Django 4.1.5 on 2023-04-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_post_comment_poll_remove_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='polls/images/'),
        ),
    ]
