# Generated by Django 4.1.5 on 2023-04-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_poll_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='image',
        ),
    ]
