# Generated by Django 4.1.5 on 2023-04-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_choice_image_choice_choice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_image',
        ),
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
