# Generated by Django 4.1.5 on 2023-04-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
