# Generated by Django 4.1.5 on 2023-04-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_rename_created_date_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollcomments', to='polls.poll'),
        ),
    ]
