# Generated by Django 4.1.5 on 2023-04-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_user_status_remove_choice_voters_delete_pollresult_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_status',
        ),
    ]
