# Generated by Django 4.1.5 on 2023-04-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_choice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
    ]
