# Generated by Django 4.1.5 on 2023-04-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_remove_choice_votes_remove_choice_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='choicevotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.IntegerField()),
            ],
        ),
    ]
