# Generated by Django 4.1.5 on 2023-04-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_choicevotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicevotes',
            old_name='poll_id',
            new_name='poll_count',
        ),
        migrations.AddField(
            model_name='choicevotes',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
    ]
