# Generated by Django 4.1.5 on 2023-04-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_rename_poll_id_choicevotes_poll_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicevotes',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='choicevotes',
            name='poll_count',
        ),
    ]
