# Generated by Django 4.1.5 on 2023-04-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_delete_choicevotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
