# Generated by Django 4.1.5 on 2023-04-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_choice_votes_choice_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='winner',
        ),
    ]
